Django-Debug-Toolbar/exercise/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('users.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

Django-Debug-Toolbar/users/urls.py
from django.conf.urls import url
from users import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^data/', views.data, name='data')
]

Django-Debug-Toolbar/users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    f_name = models.CharField(max_length=50)
    l_name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.f_name

Django-Debug-Toolbar/users/views.py
from django.shortcuts import render
from users.models import User

# Create your views here.
def index(request):
    return render(request, 'index.html')

def data(request):
    user_list = User.objects.order_by('f_name')
    data_dict = {'user_list': user_list}
    return render(request, 'data.html', data_dict)

Django-Debug-Toolbar/templates/data.html
<!DOCTYPE html>{% load staticfiles %}
<html>

<head>
    <meta charset="UTF-8">
    <title>Data page</title>
    <link rel="stylesheet" href="{% static 'css/data.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <h1>Here are your users:</h1>

        <ol>
            {% for user in user_list %}
            <li>User Info</li>
            <ul>
                <li>First Name: {{ user.f_name }}</li>
                <li>Last Name: {{ user.l_name }}</li>
                <li>Email: {{ user.email }}</li>
            </ul>
            {% endfor %}
        </ol>

    </div>
</body>

</html>

Django-Debug-Toolbar/templates/index.html
<!DOCTYPE html> {% load staticfiles %}
<html>

<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

<body>
    <h1>Welcome!</h1>
    <a href="{% url 'users:data' %}">Click Me To See Users Data</a>
</body>

</html>