cbv/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),
]

cbv/cbv/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls',namespace='basic_app'))
]

cbv/basic_app/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principle = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={"pk": self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    School = models.ForeignKey(School, related_name='students')

    def __str__(self):
        return self.name

cbv/basic_app/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.views.generic import (View, TemplateView, ListView, DetailView,
                                  CreateView,UpdateView,DeleteView)
from . import models

# simple view
# Create your views here.
# def index(request):
#     return render(request, 'index.html')

# simple CBV
# class CBView(View):
#     def get(self, request):
#         return HttpResponse('CLASS BASED VIEW')

# TemplateView
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['val'] = 'Text'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principle', 'location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principle')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')

cbv/basic_app/templates/basic_app/base_app.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>base</title>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="#"></a>
      </div>
    </nav>

<div class='container'>
     {% block body %}
    {% endblock body %}
</div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


</body>
</html>

cbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'base.html' %}

{% block body %}

<h1>Delete {{school.name}}?</h1>
<form method="post">
{% csrf_token %}
<input type="submit" class='btn btn-danger' value='delete'>
<a class="btn btn-success" href="{% url 'basic_app:detail' pk=school.pk%}">Cancel</a>

</form>


{% endblock  %}

cbv/basic_app/templates/basic_app/school_detail.html
{% extends 'base.html'%}

{% block body %}

<div class="jumbotron">
    <h1>Welcome to the school detail page</h1>
    <h2>School details</h2>
    <p>name:  {{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principle }}</p>
    <p>Location: {{ school_detail.location }}</p>
    <h3>Students:</h3>

{% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
{% endfor %}

</div>

<div class="container">
    <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
</div>

{% endblock %}

cbv/basic_app/templates/basic_app/school_form.html
{% extends 'base.html' %}

{% block body %}

<h1>
{% if not form.instance.px %}
    Create School
{% else %}
    Update School
{% endif %}

</h1>

<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary'>
</form>

{% endblock  %}

cbv/basic_app/templates/basic_app/school_list.html
{% extends 'base.html' %}

{% block body %}

<h1>List of schools</h1>

<ol>
    {% for school in schools %}
        <h2><li><a href='{{ school.id }}'>{{ school.name }}</a></li></h2>
    {% endfor %}
</ol>

{% endblock body %}

cbv/basic_app/templates/school_detail.html
{% extends 'base.html'%}

{% block body %}

<div class="jumbotron">
    <h1>Welcome to the school detail page</h1>
    <h2>School details</h2>
    <p>name:  {{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principle }}</p>
    <p>Location: {{ school_detail.location }}</p>
    <h3>Students:</h3>

{% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
{% endfor %}

</div>

{% endblock %}

cbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <title>base</title>
</head>
<body>
<div class='container'>
     {% block body %}
    {% endblock body %}
</div>

</body>
</html>

cbv/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class='jumbotron'>
    <h1>Hello world! Index Page Home</h1>
    <h2>Injected content: {{ val }}</h2>
</div>

{% endblock body %}